### ISSUE TITLE
REST API for GitHub Issues - Leverage to create a site?

### ISSUE THREAD

**Issue by Blueprinter** [brucemcpherson/desktopliberation#2]
There is a REST API for GitHub, 

https://developer.github.com/v3/issues/

and it is possible to:

list an issue
get a single issue
create an issue
edit an issue

It might be interesting to discuss how it might be possible to creating a site as the front end and use the Issues tab as the database for the site.

I'm not sure if there is a way to comment on an existing issue.  I'm not sure what the edit capabilities are.

For example, a Google Site with an embedded Apps Script Web App that could view the newest issues.  I'm sure that would be possible.  Whether it would be practical or not, I'm not sure.

**Comment by brucemcpherson** [comment]
Yes it would be possible.. the github api is excellent, and I use it a lot to manage apps script code. However its possible that we have all we need for now using the github client here.

**Comment by Blueprinter** [comment]
It's one of those things that might be on the "Wish List" but probably shouldn't take time away from more important things.  I don't know vuejs so I'd need to spend some time learning it in order to contribute.

**Comment by brucemcpherson** [comment]
Yes .. let’s see how it goes with the github issues ui.
