### ISSUE TITLE
Notifications? 

### ISSUE THREAD

**Issue by deMeeuw** [brucemcpherson/desktopliberation#3]
Any suggestion how to be informed for new 'issues', which here will equal a new post/question/insight etc. In G+ we had notifications for this.

**Comment by TonyHine** [comment]
Well as I explained in the other thread, I don't know much about GitHub! However I did just get a notification when you posted this 4 minutes ago! I believe it's because I've got the watch Button selected at the top of the screen

**Comment by deMeeuw** [comment]
Ok, mission accomplished obviously. Just open an issue, and all (?) group memebers will be notified. That's great!

**Comment by brucemcpherson** [comment]
Ok .. so now you can get a github client like GitHawk on iPad to manage notifications and make posts etc.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
