### ISSUE TITLE
Update Method for GAS as DB throwing length error

### ISSUE THREAD

**Issue by johnkelton** [brucemcpherson/desktopliberation#50]
Hi Bruce, I am having an issue with doing update method using GAS as DB. Here is my small code:
```
// do a query and update record
var result = handler.query ({ID:'A'},undefined,1,true);
if (result.handleCode < 0) throw result.handleError;
var result2 = handler.update( result.handleKeys, result.data.map (function(d) {d.NEW = 'TEST'; return d; }));
if (result2.handleCode < 0) throw result2.handleError;
}
```
My sheet does get updated with the new value but I see the following error on GAS.
`"Error:TypeError: Cannot read property 'length' of undefined\n at errorStack (Code:258:11)\n at Object.rateLimitExpBackoff (Code:245:15)" (line 274, file "Code") `
Thanks for you awesome support !!!

**Comment by brucemcpherson** [comment]
Are you using v8 ? There's been quite a few things. What version of the
libraries are you using?

**Comment by johnkelton** [comment]
Yes Sir, I am using latest versions of all libraries and V8

**Comment by brucemcpherson** [comment]
Ok - i'll take a look at it. It is most likely a v8 thing i missed.

**Comment by johnkelton** [comment]
Hey Bruce! Did you get the chance to look at the issue? Thanks

**Comment by brucemcpherson** [comment]
Sorry - i havent had a chance yet - can you a) see if it works on non-v8 b)
send me a link to the input sheet.

**Comment by johnkelton** [comment]
Thanks Bruce! for your reply. 
a) I deprecated it to DEPRECATED_ES5 but it still shows the same error.

 
Also, why am I seeing _$dbab$key$_

![image](https://user-images.githubusercontent.com/33465230/92999665-bc7f2900-f4f0-11ea-84bd-861a1b40aba9.png)

**Comment by brucemcpherson** [comment]
Thanks - I've taken a copy and I'll take a look

bruce

**Comment by johnkelton** [comment]
Hi Bruce! Were you able to find the problem? 
Thanks

**Comment by johnkelton** [comment]
Hi Bruce,
I hope you are safe. Can you please let me know how can I resolve the issue mentioned above.
Thanks

**Comment by brucemcpherson** [comment]
Hi John

thanks for chasing me up. A bit swamped right now but will check asap

happy new year
bruce

**Comment by johnkelton** [comment]
Thanks a lot Bruce. Really looking forward to work with your library.

**Comment by brucemcpherson** [comment]
Hey John - Please take a look at this test example - it's here if you want
a copy
https://script.google.com/d/1E1vbxJFKrXtNzOYL5Waxej24RysuGgGXbFUGULfsazrQEdBeCTSoSiDd/edit?usp=sharing

I've added your example more or less at the end and it works too - so I
can't replicate it. If you can't get a test like this to work on your own
sheet, you can send me the spreadsheet you're using if you want in case
there's something odd about that.

const testSheet = () => {

// make a copy of the sheet to play with
const test = makeCopy()

const handler = new cDbAbstraction.DbAbstraction(cDriverSheet, {
siloid: test.getSheet().getName(),
dbid: test.getSheet().getParent().getId(),
optout: true
});

assert ( handler.isHappy() , null, "got handler");
Logger.log('starting ' + handler.getDBName());

let result = handler.query()
assert(result.data.length === test.getNumRows(), null , "all data is there"
)

result = handler.query ({iso_country: 'CA'})
assert(result.data.length ===test.getData().filter(f=>f.iso_country === 'CA'
).length, result.data.length, 'query works' )

result = handler.query ({iso_country: 'CA'}, null , 0 , true)
assert(result.data.length ===test.getData().filter(f=>f.iso_country === 'CA'
).length, result.data.length, 'query works' )
const { driverIds, handleKeys } = result
assert(result.data.length === driverIds.length, result.data.length, 'right
number of driverIds' )
assert(driverIds.every(f=>test.getData()[f.row-1].iso_country === 'CA'),
null, 'driverids match')
assert(result.data.length === handleKeys.length, result.data.length, 'right
number of handleKeys' )

// do an update
const update = handler.update(result.handleKeys, result.data.map(f=>({
...f,
iso_country:'xx'
})))
assert(update.data.length === result.data.length, update.data.length, 'update
works' )
assert(result.data.length === handleKeys.length, result.data.length, 'right
number of handleKeys' )
// check it happened
const check = handler.query ({iso_country: 'xx'})
assert(check.data.length === result.data.length, result.data.length, 'update
query checked' )

// john test
var r = handler.query ({iso_country:'xx'},undefined,1,true);
if (r.handleCode < 0) throw r.handleError;
var result2 = handler.update( r.handleKeys, r.data.map (function(d) {d.
timestamp = 'TEST'; return d; }));
if (result2.handleCode < 0) throw result2.handleError;


}
const makeCopy = () => {

//make a copy of the sheet
const fiddler = bmPreFiddler.PreFiddler()
.getFiddler({
id: '1h9IGIShgVBVUrUjjawk5MaCEQte_7t32XeEP1Z5jXKQ',
sheetName: 'airport list'
})

const copy = bmPreFiddler.PreFiddler()
.getFiddler({
id: fiddler.getSheet().getParent().getId(),
sheetName: 'db check',
createIfMissing: true
})
copy.setData(fiddler.getData()).dumpValues()
return copy
}

**Comment by johnkelton** [comment]
Hi Bruce, I am still seeing error messages. You can access my script and google sheet here:
https://docs.google.com/spreadsheets/d/1Um2WSfFiySBRD8izN82cKNpa14E0-j3kqgt39SInn_k/edit?usp=sharing

Thanks  a lot for your help. Really appreciate it.

**Comment by brucemcpherson** [comment]
Ok - so there's a column $dbabkey or something like that - it generates a
unique key for every row and uses that to deal with updating to avoid
problems with rows being deleted etc.

I noticed in your file there are duplicate keys, so i assume you must have
copied rows and therefore made rows with duplicated keys. Just delete the
$dbabkey column.

bruce
