### ISSUE TITLE
Direct link for clone public apps script projects

### ISSUE THREAD

**Issue by oshliaer** [brucemcpherson/desktopliberation#68]
Hi Bruce!

Have you considered creating a direct link to clone the project (scrviz.web.app)? I would like to publish snippets through your application on a site. It would also help me in distributing code through chats.

**Comment by brucemcpherson** [comment]
Yes that’s a good idea. Let me think on it.

**Comment by brucemcpherson** [comment]
Hey Alex

This was a nice idea. The trickiest part was positioning the viz at the correct place for the selected Item but I have it working. I'm going to implement direct links for people and repos as well as manifests - so I should release this shortly. In any case, here's how it works
You can get a direct link to the manifest in the manifest card (or generate it -- its just the github path)
![Screenshot 2021-03-06 at 12 23 25](https://user-images.githubusercontent.com/1894020/110206764-a044bf00-7e77-11eb-80cd-8e71a0a4d9c8.png)

And pass it as a url param and it'll take you right there
![Screenshot 2021-03-06 at 12 23 47](https://user-images.githubusercontent.com/1894020/110206797-ce2a0380-7e77-11eb-83e3-d866efe73524.png)

It's nice.. thanks for the idea. Watch this space for the write up.
